# Generated by Django 2.2 on 2021-02-19 13:40

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[users.validators.user_avatar_validator], verbose_name='avatar'),
        ),
    ]
